# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test on Master Push

on:
   # Triggers the workflow on push but only for the master branch
   push:
     branches: [ main ]
   workflow_dispatch:

jobs:
  test-and-tag:
    name: Test and Tag
    runs-on: ubuntu-latest
    
    steps:
            # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
              
      - name: Set up JDK 11
        uses: actions/setup-java@v3.1.0
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
                
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashfiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: "Verify Build"
        working-directory: experimental/portappb
        run: mvn --batch-mode --update-snapshots test

      - name: "Build Container"
        working-directory: experimental/portappb
        run: mvn --batch-mode jib:dockerBuild -Pproduction
      
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
